### ISSUE TITLE
Broken .gitignore file

### ISSUE THREAD

**Issue by Paebbels** [tgingold/ghdl#498]
The changes introduced in afcf1bb0 to `.gitignore` are not correct.

```
# Generated files on windows.
./build/
./dist/mcode/build/
./dist/mcode/lib/
```

* Pattern starting with `./` do not match anything.
* The paths: `dist/mcode` do not exist anymore.  
   The correct path is `dist/mcode`. There are no sub-directories.
* The Windows build flow compiles into: `/build/mcode` and `/build/mcode/lib/*` and
* packages into `build/zip/mcode`.

Suggested `.gitignore` entries for generated files on Windows:
```
# Generated directories on Windows
build/
```

**Comment by 1138-4EB** [comment]
`build/` cannot be used, because it is interpreted as `**/build`, which leads to `dist/linux/docker/build/*` being ignored. However, as you say, `./build` does not match anything. The correct filter is `/build/`. #499 fixes this.

> The correct path is `dist/mcode`. There are no sub-directories.

Is this generated during the build process on windows, or did you mean [`dist/windows/mcode`](https://github.com/tgingold/ghdl/tree/master/dist/windows/mcode)?
